name: Bug report
description: Create a report to help us improve
title: "[BUG] Short Description"
labels: bug
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear and concise description of what you're experiencing. Do NOT combine multiple bugs into one issue. If you have multiple bugs to report please open separate issues for EACH bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll to ...
        4. See error ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots and Additional Info
      description: |
        Provide any relevant additional information such as screenshots or other details here.
        
        Tip: You can attach images files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Checklist
      description: Before submitting your bug report.
      options:
        - label: I have made a separate issue for each bug that I am reporting.
          required: true
        - label: I have searched the issues and this bug has not been reported.
          required: true